name: Release to PyPI

on:
  push:
    tags:
      - "v*.*.*"  # Runs only when a new version tag (e.g., v1.0.0) is pushed

permissions:
  id-token: write  # Required for OpenID authentication
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install build

      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
